spring.application.name=billing
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}
app.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
