spring.application.name=billing-saas
spring.profiles.active=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=7d8f3a9b2c4e6f8a1b3d5e7f9a2c4e6f8b1d3f5a7c9e2b4d6f8a1c3e5f7b9d2db3232db
app.jwt.access-token-expiration=900000
app.refresh-token-expiration=604800000

app.super-admin.email=superadmin@billing.local
app.super-admin.password=SuperAdmin@123
app.super-admin.name=Platform Super Admin
