package com.billing.service.invoice;

import com.billing.dto.invoice.CompanyInvoiceSettingsRequest;
import com.billing.dto.invoice.CompanyInvoiceSettingsResponse;
import com.billing.entity.Company;
import com.billing.entity.CompanyInvoiceSetting;
import com.billing.repository.CompanyInvoiceSettingRepository;
import com.billing.service.AccessControlService;
import com.billing.util.DataTypeUtility;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Map;

@Service
@RequiredArgsConstructor
public class CompanyInvoiceSettingsService {

    private final AccessControlService accessControlService;
    private final CompanyInvoiceSettingRepository companyInvoiceSettingRepository;
    private final InvoiceTemplateRegistryService invoiceTemplateRegistryService;

    @Transactional(readOnly = true)
    public CompanyInvoiceSettingsResponse get(String email) {
        Company company = accessControlService.getCurrentCompany(email);
        return toResponse(resolveOrDefault(company));
    }

    @Transactional
    public CompanyInvoiceSettingsResponse update(Map<String, Object> param, String email) {
        CompanyInvoiceSettingsRequest companyInvoiceSettingsRequest = mapToRequest(param);
        return update(email, companyInvoiceSettingsRequest);
    }

    @Transactional
    public CompanyInvoiceSettingsResponse update(String email, CompanyInvoiceSettingsRequest request) {
        Company company = accessControlService.getCurrentCompany(email);
        invoiceTemplateRegistryService.getOrThrow(request.getDefaultTemplateId());
        CompanyInvoiceSetting setting = resolveForUpdate(company);
        setting.setDefaultTemplateId(request.getDefaultTemplateId());
        setting.setShowWatermark(Boolean.TRUE.equals(request.getShowWatermark()));
        setting.setWatermarkText(blankToNull(request.getWatermarkText()));
        setting.setShowSignature(request.getShowSignature() == null || request.getShowSignature());
        setting.setSignatureLabel(normalizeOptionalText(request.getSignatureLabel()));
        setting.setSignatureHeading(normalizeOptionalText(request.getSignatureHeading()));
        setting.setShowQr(request.getShowQr() == null || request.getShowQr());
        setting.setShowBankDetails(request.getShowBankDetails() == null || request.getShowBankDetails());
        setting.setShowTerms(request.getShowTerms() == null || request.getShowTerms());
        setting.setShowNotes(request.getShowNotes() == null || request.getShowNotes());
        setting.setNoteText(normalizeOptionalText(request.getNoteText()));
        setting.setTermsText(normalizeOptionalText(request.getTermsText()));
        setting.setFooterCredit(normalizeOptionalText(request.getFooterCredit()));
        return toResponse(companyInvoiceSettingRepository.save(setting));
    }

    @Transactional(readOnly = true)
    public CompanyInvoiceSetting resolveForCompany(Company company) {
        return resolveOrDefault(company);
    }

    private CompanyInvoiceSetting resolveForUpdate(Company company) {
        return companyInvoiceSettingRepository.findByCompany(company)
                .orElseGet(() -> companyInvoiceSettingRepository.save(CompanyInvoiceSetting.builder()
                        .company(company)
                        .defaultTemplateId(invoiceTemplateRegistryService.defaultTemplateId())
                        .showWatermark(false)
                        .showSignature(true)
                        .signatureLabel("Authorized Signature")
                        .signatureHeading("For Company")
                        .showQr(true)
                        .showBankDetails(true)
                        .showTerms(true)
                        .showNotes(true)
                        .noteText("Thank you for choosing Bizio.")
                        .termsText("Goods once sold will not be taken back.")
                        .footerCredit("Generated by Bizio Billing SaaS")
                        .build()));
    }

    private CompanyInvoiceSetting resolveOrDefault(Company company) {
        return companyInvoiceSettingRepository.findByCompany(company)
                .orElseGet(() -> CompanyInvoiceSetting.builder()
                        .company(company)
                        .defaultTemplateId(invoiceTemplateRegistryService.defaultTemplateId())
                        .showWatermark(false)
                        .showSignature(true)
                        .signatureLabel("Authorized Signature")
                        .signatureHeading("For Company")
                        .showQr(true)
                        .showBankDetails(true)
                        .showTerms(true)
                        .showNotes(true)
                        .noteText("Thank you for choosing Bizio.")
                        .termsText("Goods once sold will not be taken back.")
                        .footerCredit("Generated by Bizio Billing SaaS")
                        .build());
    }

    private CompanyInvoiceSettingsResponse toResponse(CompanyInvoiceSetting setting) {
        return CompanyInvoiceSettingsResponse.builder()
                .defaultTemplateId(setting.getDefaultTemplateId())
                .showWatermark(setting.isShowWatermark())
                .watermarkText(setting.getWatermarkText())
                .showSignature(setting.isShowSignature())
                .signatureLabel(defaultIfNull(setting.getSignatureLabel(), "Authorized Signature"))
                .signatureHeading(defaultIfNull(setting.getSignatureHeading(), "For Company"))
                .showQr(setting.isShowQr())
                .showBankDetails(setting.isShowBankDetails())
                .showTerms(setting.isShowTerms())
                .showNotes(setting.isShowNotes())
                .noteText(defaultIfNull(setting.getNoteText(), "Thank you for choosing Bizio."))
                .termsText(defaultIfNull(setting.getTermsText(), "Goods once sold will not be taken back."))
                .footerCredit(defaultIfNull(setting.getFooterCredit(), "Generated by Bizio Billing SaaS"))
                .build();
    }

    private String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

    private String normalizeOptionalText(String value) {
        return value == null ? null : value.trim();
    }

    private String defaultIfNull(String value, String defaultValue) {
        return value == null ? defaultValue : value;
    }

    private CompanyInvoiceSettingsRequest mapToRequest(Map<String, Object> param) {
        CompanyInvoiceSettingsRequest companyInvoiceSettingsRequest = new CompanyInvoiceSettingsRequest();
        String defaultTemplateId = DataTypeUtility.stringValue(param.get("defaultTemplateId"));
        if (defaultTemplateId.length() == 0) {
            defaultTemplateId = null;
        }
        companyInvoiceSettingsRequest.setDefaultTemplateId(defaultTemplateId);
        Object showWatermarkObj = param.get("showWatermark");
        if (showWatermarkObj != null) {
            String showWatermarkStr = DataTypeUtility.stringValue(showWatermarkObj);
            if (showWatermarkStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowWatermark(DataTypeUtility.booleanValue(showWatermarkObj));
            }
        }
        String watermarkText = DataTypeUtility.stringValue(param.get("watermarkText"));
        if (watermarkText.length() == 0) {
            watermarkText = null;
        }
        companyInvoiceSettingsRequest.setWatermarkText(watermarkText);
        Object showSignatureObj = param.get("showSignature");
        if (showSignatureObj != null) {
            String showSignatureStr = DataTypeUtility.stringValue(showSignatureObj);
            if (showSignatureStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowSignature(DataTypeUtility.booleanValue(showSignatureObj));
            }
        }
        String signatureLabel = DataTypeUtility.stringValue(param.get("signatureLabel"));
        if (signatureLabel.length() == 0) {
            signatureLabel = null;
        }
        companyInvoiceSettingsRequest.setSignatureLabel(signatureLabel);
        String signatureHeading = DataTypeUtility.stringValue(param.get("signatureHeading"));
        if (signatureHeading.length() == 0) {
            signatureHeading = null;
        }
        companyInvoiceSettingsRequest.setSignatureHeading(signatureHeading);
        Object showQrObj = param.get("showQr");
        if (showQrObj != null) {
            String showQrStr = DataTypeUtility.stringValue(showQrObj);
            if (showQrStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowQr(DataTypeUtility.booleanValue(showQrObj));
            }
        }
        Object showBankDetailsObj = param.get("showBankDetails");
        if (showBankDetailsObj != null) {
            String showBankDetailsStr = DataTypeUtility.stringValue(showBankDetailsObj);
            if (showBankDetailsStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowBankDetails(DataTypeUtility.booleanValue(showBankDetailsObj));
            }
        }
        Object showTermsObj = param.get("showTerms");
        if (showTermsObj != null) {
            String showTermsStr = DataTypeUtility.stringValue(showTermsObj);
            if (showTermsStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowTerms(DataTypeUtility.booleanValue(showTermsObj));
            }
        }
        Object showNotesObj = param.get("showNotes");
        if (showNotesObj != null) {
            String showNotesStr = DataTypeUtility.stringValue(showNotesObj);
            if (showNotesStr.length() > 0) {
                companyInvoiceSettingsRequest.setShowNotes(DataTypeUtility.booleanValue(showNotesObj));
            }
        }
        String noteText = DataTypeUtility.stringValue(param.get("noteText"));
        if (noteText.length() == 0) {
            noteText = null;
        }
        companyInvoiceSettingsRequest.setNoteText(noteText);
        String termsText = DataTypeUtility.stringValue(param.get("termsText"));
        if (termsText.length() == 0) {
            termsText = null;
        }
        companyInvoiceSettingsRequest.setTermsText(termsText);
        String footerCredit = DataTypeUtility.stringValue(param.get("footerCredit"));
        if (footerCredit.length() == 0) {
            footerCredit = null;
        }
        companyInvoiceSettingsRequest.setFooterCredit(footerCredit);
        return companyInvoiceSettingsRequest;
    }
}
