package com.billing.service.invoice;

import com.billing.dto.invoice.CompanyInvoiceSettingsRequest;
import com.billing.dto.invoice.CompanyInvoiceSettingsResponse;
import com.billing.entity.Company;
import com.billing.entity.CompanyInvoiceSetting;
import com.billing.repository.CompanyInvoiceSettingRepository;
import com.billing.service.AccessControlService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class CompanyInvoiceSettingsService {

    private final AccessControlService accessControlService;
    private final CompanyInvoiceSettingRepository companyInvoiceSettingRepository;
    private final InvoiceTemplateRegistryService invoiceTemplateRegistryService;

    @Transactional(readOnly = true)
    public CompanyInvoiceSettingsResponse get(String email) {
        Company company = accessControlService.getCurrentCompany(email);
        return toResponse(resolveOrDefault(company));
    }

    @Transactional
    public CompanyInvoiceSettingsResponse update(String email, CompanyInvoiceSettingsRequest request) {
        Company company = accessControlService.getCurrentCompany(email);
        invoiceTemplateRegistryService.getOrThrow(request.getDefaultTemplateId());
        CompanyInvoiceSetting setting = resolveForUpdate(company);
        setting.setDefaultTemplateId(request.getDefaultTemplateId());
        setting.setShowWatermark(Boolean.TRUE.equals(request.getShowWatermark()));
        setting.setWatermarkText(blankToNull(request.getWatermarkText()));
        setting.setShowSignature(request.getShowSignature() == null || request.getShowSignature());
        setting.setSignatureLabel(normalizeOptionalText(request.getSignatureLabel()));
        setting.setSignatureHeading(normalizeOptionalText(request.getSignatureHeading()));
        setting.setShowQr(request.getShowQr() == null || request.getShowQr());
        setting.setShowBankDetails(request.getShowBankDetails() == null || request.getShowBankDetails());
        setting.setShowTerms(request.getShowTerms() == null || request.getShowTerms());
        setting.setShowNotes(request.getShowNotes() == null || request.getShowNotes());
        setting.setNoteText(normalizeOptionalText(request.getNoteText()));
        setting.setTermsText(normalizeOptionalText(request.getTermsText()));
        setting.setFooterCredit(normalizeOptionalText(request.getFooterCredit()));
        return toResponse(companyInvoiceSettingRepository.save(setting));
    }

    @Transactional(readOnly = true)
    public CompanyInvoiceSetting resolveForCompany(Company company) {
        return resolveOrDefault(company);
    }

    private CompanyInvoiceSetting resolveForUpdate(Company company) {
        return companyInvoiceSettingRepository.findByCompany(company)
                .orElseGet(() -> companyInvoiceSettingRepository.save(CompanyInvoiceSetting.builder()
                        .company(company)
                        .defaultTemplateId(invoiceTemplateRegistryService.defaultTemplateId())
                        .showWatermark(false)
                        .showSignature(true)
                        .signatureLabel("Authorized Signature")
                        .signatureHeading("For Company")
                        .showQr(true)
                        .showBankDetails(true)
                        .showTerms(true)
                        .showNotes(true)
                        .noteText("Thank you for choosing BizFinity.")
                        .termsText("Goods once sold will not be taken back.")
                        .footerCredit("Generated by BizFinity Billing SaaS")
                        .build()));
    }

    private CompanyInvoiceSetting resolveOrDefault(Company company) {
        return companyInvoiceSettingRepository.findByCompany(company)
                .orElseGet(() -> CompanyInvoiceSetting.builder()
                        .company(company)
                        .defaultTemplateId(invoiceTemplateRegistryService.defaultTemplateId())
                        .showWatermark(false)
                        .showSignature(true)
                        .signatureLabel("Authorized Signature")
                        .signatureHeading("For Company")
                        .showQr(true)
                        .showBankDetails(true)
                        .showTerms(true)
                        .showNotes(true)
                        .noteText("Thank you for choosing BizFinity.")
                        .termsText("Goods once sold will not be taken back.")
                        .footerCredit("Generated by BizFinity Billing SaaS")
                        .build());
    }

    private CompanyInvoiceSettingsResponse toResponse(CompanyInvoiceSetting setting) {
        return CompanyInvoiceSettingsResponse.builder()
                .defaultTemplateId(setting.getDefaultTemplateId())
                .showWatermark(setting.isShowWatermark())
                .watermarkText(setting.getWatermarkText())
                .showSignature(setting.isShowSignature())
                .signatureLabel(defaultIfNull(setting.getSignatureLabel(), "Authorized Signature"))
                .signatureHeading(defaultIfNull(setting.getSignatureHeading(), "For Company"))
                .showQr(setting.isShowQr())
                .showBankDetails(setting.isShowBankDetails())
                .showTerms(setting.isShowTerms())
                .showNotes(setting.isShowNotes())
                .noteText(defaultIfNull(setting.getNoteText(), "Thank you for choosing BizFinity."))
                .termsText(defaultIfNull(setting.getTermsText(), "Goods once sold will not be taken back."))
                .footerCredit(defaultIfNull(setting.getFooterCredit(), "Generated by BizFinity Billing SaaS"))
                .build();
    }

    private String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

    private String normalizeOptionalText(String value) {
        return value == null ? null : value.trim();
    }

    private String defaultIfNull(String value, String defaultValue) {
        return value == null ? defaultValue : value;
    }
}
