DELETE FROM user_permission
WHERE app_menu_id IN (
    SELECT id FROM app_menu
    WHERE menu_code IN ('SUPER_ADMIN_DASHBOARD', 'SUPER_ADMIN_COMPANIES', 'SUPER_ADMIN_USERS', 'SUPER_ADMIN_COMPANY_DETAILS')
);

DELETE FROM role_menu_action_permission
WHERE app_menu_id IN (
    SELECT id FROM app_menu
    WHERE menu_code IN ('SUPER_ADMIN_DASHBOARD', 'SUPER_ADMIN_COMPANIES', 'SUPER_ADMIN_USERS', 'SUPER_ADMIN_COMPANY_DETAILS')
);

DELETE FROM role_menu_permission
WHERE app_menu_id IN (
    SELECT id FROM app_menu
    WHERE menu_code IN ('SUPER_ADMIN_DASHBOARD', 'SUPER_ADMIN_COMPANIES', 'SUPER_ADMIN_USERS', 'SUPER_ADMIN_COMPANY_DETAILS')
);

DELETE FROM app_menu_action
WHERE app_menu_id IN (
    SELECT id FROM app_menu
    WHERE menu_code IN ('SUPER_ADMIN_DASHBOARD', 'SUPER_ADMIN_COMPANIES', 'SUPER_ADMIN_USERS', 'SUPER_ADMIN_COMPANY_DETAILS')
);

DELETE FROM app_menu
WHERE menu_code IN ('SUPER_ADMIN_DASHBOARD', 'SUPER_ADMIN_COMPANIES', 'SUPER_ADMIN_USERS', 'SUPER_ADMIN_COMPANY_DETAILS');
