ALTER TABLE companies
    ADD COLUMN inventory_consumption_method VARCHAR(32) NOT NULL DEFAULT 'FIFO',
    ADD COLUMN inventory_pricing_policy VARCHAR(64) NOT NULL DEFAULT 'LATEST_BATCH_SELLING_PRICE';

CREATE TABLE purchases (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    purchase_no VARCHAR(80) NOT NULL,
    purchase_date DATE NOT NULL,
    supplier_name VARCHAR(255) NULL,
    remarks VARCHAR(500) NULL,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    CONSTRAINT uk_purchases_company_purchase_no UNIQUE (company_id, purchase_no),
    CONSTRAINT fk_purchases_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE purchase_items (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    purchase_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    qty INT NOT NULL,
    purchase_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    selling_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    CONSTRAINT fk_purchase_items_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE product_batches (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    purchase_id BIGINT NULL,
    purchase_item_id BIGINT NULL,
    batch_no VARCHAR(100) NOT NULL,
    batch_date DATE NOT NULL,
    purchase_qty INT NOT NULL,
    remaining_qty INT NOT NULL,
    purchase_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    selling_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    batch_status VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    CONSTRAINT uk_product_batches_company_batch_no UNIQUE (company_id, batch_no),
    CONSTRAINT fk_product_batches_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_product_batches_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_batches_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_product_batches_purchase_item FOREIGN KEY (purchase_item_id) REFERENCES purchase_items (id)
);

CREATE TABLE invoice_item_allocations (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,
    invoice_item_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_batch_id BIGINT NOT NULL,
    allocated_qty INT NOT NULL,
    purchase_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    selling_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cost_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    active BIT(1) NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    CONSTRAINT fk_invoice_item_allocations_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_invoice_item_allocations_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id),
    CONSTRAINT fk_invoice_item_allocations_invoice_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items (id),
    CONSTRAINT fk_invoice_item_allocations_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_invoice_item_allocations_batch FOREIGN KEY (product_batch_id) REFERENCES product_batches (id)
);

CREATE TABLE inventory_ledger (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_batch_id BIGINT NULL,
    purchase_id BIGINT NULL,
    purchase_item_id BIGINT NULL,
    invoice_id BIGINT NULL,
    invoice_item_id BIGINT NULL,
    invoice_allocation_id BIGINT NULL,
    movement_type VARCHAR(40) NOT NULL,
    entry_date DATE NOT NULL,
    qty_in INT NOT NULL DEFAULT 0,
    qty_out INT NOT NULL DEFAULT 0,
    balance_after INT NOT NULL DEFAULT 0,
    unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    reference_no VARCHAR(100) NULL,
    remarks VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    CONSTRAINT fk_inventory_ledger_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_inventory_ledger_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inventory_ledger_batch FOREIGN KEY (product_batch_id) REFERENCES product_batches (id),
    CONSTRAINT fk_inventory_ledger_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_inventory_ledger_purchase_item FOREIGN KEY (purchase_item_id) REFERENCES purchase_items (id),
    CONSTRAINT fk_inventory_ledger_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id),
    CONSTRAINT fk_inventory_ledger_invoice_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items (id),
    CONSTRAINT fk_inventory_ledger_allocation FOREIGN KEY (invoice_allocation_id) REFERENCES invoice_item_allocations (id)
);
